PROJECT = Alnilam
ARDUINO_PORT = /dev/ttyS10
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE = 19200
ARDUINO_CORE_PATH = ../tiny/cores/tiny
ARDUINO_LIBS = EEPROM TinyWireS
BOARDS_TXT = ../tiny/boards.txt 
BOARD_TAG = attiny45at8
include ../Arduino.mk
